# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [--preview]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.20.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.3.0
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [
          "dlint~=0.16.0 ",
          "flake8-async~=25.5.1",
#          "flake8-bandit~=4.1.1",
          "flake8-bugbear~=24.12.12 ",
          "flake8-comprehensions~=3.16.0",
          "flake8-eradicate~=1.5.0",
          "flake8-noqa~=1.4.0",
#          "flake8-pie~=0.16.0",
          "flake8-pytest-style~=2.1.0",
          "flake8-self~=0.2.2",
          "flake8-simplify~=0.22.0",
          "flake8-type-checking~=3.0.0",
          "flake8-typing-imports~=1.16.0",
#          "flake8-unused-arguments~=0.0.13",
          "flake8-warnings~=0.4.1",
          "pep8-naming~=0.15.1",
        ]
