---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
    args:
      - PYTHON_VERSION=${PYTHON_VERSION:-3.14}
  image: "picodi:dev"
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity
